name: update-hanviet-dict

on: 
  push:
    branchs:
      - "main"
    paths:
      - "resource/**"

jobs:
  generate-hanviet-dict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install kyujipy --ignore-requires-python
      - name: Generate hanviet dict
        run: |
          python ./create_hanviet_dict.py

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add *
          git commit -m "Update hanviet dict"
          git pull --rebase origin ${{ github.ref_name }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


  